#pragma once

#include "CoreMinimal.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"

#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

namespace NeoLuaPin
{
	// Get a usable pin name for Lua consumers.
	// Priority: display name (if substantive) > PinName (if substantive) > directional index fallback.
	// Material/SoundCue set PinFriendlyName to " " (space) for unnamed pins, so we skip whitespace-only names.
	inline FString GetUsablePinName(UEdGraphPin* Pin)
	{
		// 1. Try display name (friendly name shown in editor)
		FString DisplayName = Pin->GetDisplayName().ToString();
		if (!DisplayName.TrimStartAndEnd().IsEmpty())
		{
			return DisplayName;
		}

		// 2. Try PinName (internal name, e.g. "Output_0", "Input2", "RGB")
		FString PinName = Pin->PinName.ToString();
		if (!PinName.TrimStartAndEnd().IsEmpty())
		{
			return PinName;
		}

		// 3. Generate a directional index fallback (in_0, out_0, etc.)
		UEdGraphNode* Node = Pin->GetOwningNodeUnchecked();
		int32 Idx = 0;
		if (Node)
		{
			for (UEdGraphPin* P : Node->Pins)
			{
				if (P == Pin) break;
				if (P && P->Direction == Pin->Direction) Idx++;
			}
		}
		return (Pin->Direction == EGPD_Input)
			? FString::Printf(TEXT("in_%d"), Idx)
			: FString::Printf(TEXT("out_%d"), Idx);
	}

	inline sol::table BuildPinTable(sol::state_view& LuaView, UEdGraphPin* Pin, bool bIncludeHiddenLinks = true)
	{
		FString PinName = GetUsablePinName(Pin);

		sol::table PinInfo = LuaView.create_table();
		PinInfo["name"] = TCHAR_TO_UTF8(*PinName);
		// Also expose the raw internal name for debugging
		PinInfo["raw_name"] = TCHAR_TO_UTF8(*Pin->PinName.ToString());
		PinInfo["type"] = TCHAR_TO_UTF8(*Pin->PinType.PinCategory.ToString());
		if (Pin->PinType.PinSubCategoryObject.IsValid())
		{
			PinInfo["sub_type"] = TCHAR_TO_UTF8(*Pin->PinType.PinSubCategoryObject->GetName());
		}
		else if (!Pin->PinType.PinSubCategory.IsNone())
		{
			PinInfo["sub_type"] = TCHAR_TO_UTF8(*Pin->PinType.PinSubCategory.ToString());
		}
		if (Pin->PinType.ContainerType == EPinContainerType::Array)
			PinInfo["container"] = "array";
		else if (Pin->PinType.ContainerType == EPinContainerType::Set)
			PinInfo["container"] = "set";
		else if (Pin->PinType.ContainerType == EPinContainerType::Map)
			PinInfo["container"] = "map";
		// Use GetDefaultAsString() to unify string values and object references
		// (class/object pins store value in DefaultObject, not DefaultValue)
		FString DefaultStr = Pin->GetDefaultAsString();
		if (!DefaultStr.IsEmpty())
		{
			PinInfo["default"] = TCHAR_TO_UTF8(*DefaultStr);
		}
		PinInfo["connected"] = Pin->HasAnyConnections();
		if (Pin->DefaultObject)
		{
			// Keep for backward compat — agents may check this field
			PinInfo["default_object"] = TCHAR_TO_UTF8(*Pin->DefaultObject->GetPathName());
		}
		if (!Pin->DefaultTextValue.IsEmpty())
		{
			PinInfo["default_text"] = TCHAR_TO_UTF8(*Pin->DefaultTextValue.ToString());
		}
		if (!Pin->AutogeneratedDefaultValue.IsEmpty())
		{
			PinInfo["autogenerated_default"] = TCHAR_TO_UTF8(*Pin->AutogeneratedDefaultValue);
		}
		PinInfo["is_hidden"] = static_cast<bool>(Pin->bHidden);
		PinInfo["is_orphaned"] = static_cast<bool>(Pin->bOrphanedPin);
		if (Pin->bAdvancedView) PinInfo["is_advanced"] = true;
		PinInfo["direction"] = (Pin->Direction == EGPD_Input) ? "input" : "output";
		PinInfo["linked_to_count"] = Pin->LinkedTo.Num();
		if (Pin->LinkedTo.Num() > 0)
		{
			sol::table LinkedToTable = LuaView.create_table();
			int32 LtIdx = 1;
			for (UEdGraphPin* LinkedPin : Pin->LinkedTo)
			{
				if (!LinkedPin || (!bIncludeHiddenLinks && LinkedPin->bHidden)) continue;
				UEdGraphNode* LinkedNode = LinkedPin->GetOwningNodeUnchecked();
				if (!LinkedNode) continue;
				sol::table LtEntry = LuaView.create_table();
				LtEntry["node_id"] = TCHAR_TO_UTF8(*LinkedNode->NodeGuid.ToString());
				LtEntry["node_title"] = TCHAR_TO_UTF8(*LinkedNode->GetNodeTitle(ENodeTitleType::ListView).ToString());
				LtEntry["pin_name"] = TCHAR_TO_UTF8(*GetUsablePinName(LinkedPin));
				LinkedToTable[LtIdx++] = LtEntry;
			}
			PinInfo["linked_to"] = LinkedToTable;
		}
		if (Pin->PinType.bIsReference) PinInfo["is_reference"] = true;
		if (Pin->PinType.bIsConst) PinInfo["is_const"] = true;
		if (Pin->PinType.bIsWeakPointer) PinInfo["is_weak_pointer"] = true;
		if (Pin->PinType.ContainerType == EPinContainerType::Map && Pin->PinType.PinValueType.TerminalCategory != NAME_None)
		{
			PinInfo["value_type"] = TCHAR_TO_UTF8(*Pin->PinType.PinValueType.TerminalCategory.ToString());
			if (Pin->PinType.PinValueType.TerminalSubCategoryObject.IsValid())
				PinInfo["value_sub_type"] = TCHAR_TO_UTF8(*Pin->PinType.PinValueType.TerminalSubCategoryObject->GetName());
		}
		// Expose split sub-pins (e.g. Vector → X/Y/Z) so agents see the full picture
		if (Pin->SubPins.Num() > 0)
		{
			sol::table SubPinsTable = LuaView.create_table();
			int32 SubIdx = 1;
			for (UEdGraphPin* SubPin : Pin->SubPins)
			{
				if (!SubPin || (!bIncludeHiddenLinks && SubPin->bHidden)) continue;
				SubPinsTable[SubIdx++] = BuildPinTable(LuaView, SubPin, bIncludeHiddenLinks);
			}
			PinInfo["sub_pins"] = SubPinsTable;
		}
		return PinInfo;
	}

	// Resolve a pin by name on a node using flexible matching:
	//   1. Exec aliases: "execute"/"exec" → first input exec pin; "then"/"output exec" → first output exec pin
	//      (aliases resolve to a specific direction; the Direction argument is ignored when they match)
	//   2. Exact PinName
	//   3. Exact DisplayName
	//   4. Exact UsablePinName (handles "in_0"/"out_0" fallbacks for blank-named pins)
	//   5. Case-insensitive match against all three name sources
	// Direction=EGPD_MAX searches both directions. Hidden pins are skipped.
	inline UEdGraphPin* Find(UEdGraphNode* Node, const FString& PinName, EEdGraphPinDirection Direction = EGPD_MAX)
	{
		if (!Node) return nullptr;

		const FString Lower = PinName.ToLower();
		if (Lower == TEXT("execute") || Lower == TEXT("exec"))
		{
			return Node->FindPinByPredicate([](UEdGraphPin* Pin)
			{
				return Pin && Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec && Pin->Direction == EGPD_Input;
			});
		}
		if (Lower == TEXT("then") || Lower == TEXT("output exec"))
		{
			return Node->FindPinByPredicate([](UEdGraphPin* Pin)
			{
				return Pin && Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec && Pin->Direction == EGPD_Output;
			});
		}

		const auto DirOk = [Direction](UEdGraphPin* Pin)
		{
			return Direction == EGPD_MAX || Pin->Direction == Direction;
		};

		// Tier 1: exact PinName
		if (UEdGraphPin* Found = Node->FindPinByPredicate([&](UEdGraphPin* Pin)
			{ return Pin && !Pin->bHidden && DirOk(Pin) && Pin->PinName.ToString() == PinName; }))
		{
			return Found;
		}
		// Tier 2: exact DisplayName
		if (UEdGraphPin* Found = Node->FindPinByPredicate([&](UEdGraphPin* Pin)
			{ return Pin && !Pin->bHidden && DirOk(Pin) && Pin->GetDisplayName().ToString() == PinName; }))
		{
			return Found;
		}
		// Tier 3: exact UsablePinName
		if (UEdGraphPin* Found = Node->FindPinByPredicate([&](UEdGraphPin* Pin)
			{ return Pin && !Pin->bHidden && DirOk(Pin) && GetUsablePinName(Pin) == PinName; }))
		{
			return Found;
		}
		// Tier 4: case-insensitive across all three
		return Node->FindPinByPredicate([&](UEdGraphPin* Pin)
		{
			if (!Pin || Pin->bHidden || !DirOk(Pin)) return false;
			return Pin->PinName.ToString().Equals(PinName, ESearchCase::IgnoreCase)
				|| Pin->GetDisplayName().ToString().Equals(PinName, ESearchCase::IgnoreCase)
				|| GetUsablePinName(Pin).Equals(PinName, ESearchCase::IgnoreCase);
		});
	}

	// Format the node's visible pins for error-message display.
	// Direction=EGPD_MAX lists both directions.
	// bShowDirection=true appends "(in|out)"; bShowType=true additionally includes "type<subtype>".
	// Format matrix: neither → "Name"; direction only → "Name (in)"; both → "Name (in, exec<...>)".
	inline FString ListAvailable(UEdGraphNode* Node, EEdGraphPinDirection Direction = EGPD_MAX,
		bool bShowDirection = true, bool bShowType = true)
	{
		if (!Node) return FString();
		FString List;
		for (UEdGraphPin* Pin : Node->Pins)
		{
			if (!Pin || Pin->bHidden) continue;
			if (Direction != EGPD_MAX && Pin->Direction != Direction) continue;

			if (List.Len() > 0) List += TEXT(", ");
			FString Name = GetUsablePinName(Pin);
			if (!bShowDirection)
			{
				List += Name;
				continue;
			}
			FString Dir = Pin->Direction == EGPD_Input ? TEXT("in") : TEXT("out");
			if (bShowType)
			{
				FString Type = Pin->PinType.PinCategory.ToString();
				if (Pin->PinType.PinSubCategoryObject.IsValid())
				{
					Type += FString::Printf(TEXT("<%s>"), *Pin->PinType.PinSubCategoryObject->GetName());
				}
				List += FString::Printf(TEXT("%s (%s, %s)"), *Name, *Dir, *Type);
			}
			else
			{
				List += FString::Printf(TEXT("%s (%s)"), *Name, *Dir);
			}
		}
		return List;
	}

	// Unified sol::object → FString coercion used across binding sites (set_pin, set_node_property,
	// add_variable, bp:set, bp:configure_widget). Integer doubles format as %lld, fractional as %g.
	// Returns empty string for unsupported types (table/nil/userdata).
	inline FString SolToString(const sol::object& Obj)
	{
		if (Obj.is<std::string>()) return UTF8_TO_TCHAR(Obj.as<std::string>().c_str());
		if (Obj.is<bool>()) return Obj.as<bool>() ? TEXT("true") : TEXT("false");
		if (Obj.is<double>())
		{
			double V = Obj.as<double>();
			if (FMath::IsNearlyEqual(V, FMath::RoundToDouble(V)))
				return FString::Printf(TEXT("%lld"), (long long)V);
			return FString::Printf(TEXT("%g"), V);
		}
		return FString();
	}
}
